# Generated by Django 2.0.1 on 2018-01-31 12:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0002_auto_20180131_1103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='normaluser',
            name='id',
        ),
        migrations.AlterField(
            model_name='normaluser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
