# Generated by Django 2.0.1 on 2018-01-31 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0007_auto_20180131_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='normaluser',
            name='date_of_birth',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='normaluser',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='userprofiles/profile_pics'),
        ),
    ]
