# Generated by Django 2.0.1 on 2018-03-16 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0011_auto_20180131_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='display_status',
            field=models.TextField(blank=True, null=True),
        ),
    ]
