# Generated by Django 2.0.1 on 2018-03-16 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0012_profile_display_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='display_status',
            field=models.TextField(default='Hey there! Welcome to my profile!'),
        ),
    ]
