# Generated by Django 2.0.1 on 2018-03-30 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_auto_20180330_1153'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='restaurant_pic',
            new_name='cover_pic',
        ),
    ]
