# Generated by Django 2.0.1 on 2018-03-30 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_auto_20180330_1306'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='user',
            new_name='writer',
        ),
    ]
